name: mvp_phoniron
description: "phoniron project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  badges: ^3.1.2
  dependency_validator: ^4.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_easy_faq: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  icon_badge: ^1.0.0
  material_design_icons_flutter: ^7.0.7296
  phosphor_flutter: ^2.1.0
  rename_app: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"

flutter_native_splash:
  color: "#006973"
  image: assets/logos/logo_white.png
  android_12:
    color: "#006973"
    image: assets/logos/logo_white.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/country_flags/
    - assets/backgrounds/
    - assets/app_elements/
    - assets/app_icons/
    - assets/logos/
